<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataUser = [
            ['user_id' => 2, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-06-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 3, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-02-03', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 4, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1999-05-30', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 5, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-12-02', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 6, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-06-04', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 7, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-01-18', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 8, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2002-05-12', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 9, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-10-09', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 10, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-12-02', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 11, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2001-11-19', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 12, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2001-11-27', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 13, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1997-06-28', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 14, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-04-28', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 15, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-04-12', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 16, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1997-04-12', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 17, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-08-08', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 18, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-06-13', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 19, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-12-22', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 20, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-05-04', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 21, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-02-24', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 22, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-05-28', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 23, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-11-26', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 24, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-07-16', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 25, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-11-25', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 26, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-08-12', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 27, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1998-11-25', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 28, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2002-03-05', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 29, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-05-22', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 30, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-04-06', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 31, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-09-15', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 32, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-08-16', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 33, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1989-04-02', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 34, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2001-01-24', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 35, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-04-26', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 36, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2002-03-07', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 37, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1993-03-25', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 38, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '1999-02-06', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 39, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-09-25', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 40, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1991-07-15', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 41, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-05-27', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 42, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-05-02', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 43, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-05-25', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 44, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-01-01', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 45, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-11-02', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 46, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-11-18', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 47, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-04-10', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 48, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-03-10', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 49, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2000-10-20', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 50, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2001-07-29', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 51, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2001-06-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 52, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2002-01-05', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 53, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-04-29', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 54, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-10-17', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 55, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1997-08-15', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 56, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-09-05', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 57, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-06-09', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 58, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-05-31', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 59, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2003-02-21', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 60, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2001-03-18', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 61, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-10-09', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 62, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-10-11', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 63, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1997-04-16', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 64, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-02-26', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 65, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1998-12-23', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 66, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-01-05', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 67, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-09-30', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 68, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-12-04', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 69, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-09-15', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 70, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-05-06', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 71, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-07-27', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 72, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1997-08-07', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 73, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1989-12-03', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 74, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-11-15', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 75, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2002-08-16', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 76, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2000-02-05', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 77, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1999-03-01', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 78, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1991-07-30', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 79, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '1992-10-21', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 80, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '1993-09-26', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 81, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-10-30', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 82, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2003-07-04', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 83, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2005-05-19', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 84, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2005-11-09', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 85, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-05-04', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 86, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-09-03', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 87, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-07-03', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 88, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-12-30', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 89, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2006-05-10', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 90, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-03-29', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 91, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-10-06', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 92, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-10-25', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 93, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-03-17', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 94, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-05-01', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 95, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2003-09-12', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 96, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-07-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 97, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-01-31', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 98, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-01-12', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 99, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-07-10', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 100, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-06-24', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 101, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-05-10', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 102, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2003-08-21', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 103, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-03-01', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 104, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-04-22', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 105, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-03-24', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 106, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-07-30', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 107, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-05-15', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 108, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-11-13', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 109, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2001-06-05', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 110, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2001-09-04', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 111, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-01-26', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 112, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-11-08', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 113, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-07-25', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 114, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-04-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 115, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2003-04-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 116, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-10-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 117, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-07-12', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 118, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-08-18', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 119, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-11-27', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 120, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2002-06-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 121, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1997-11-06', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 122, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-11-24', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 123, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-02-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 124, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-01-24', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 125, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1995-05-07', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 126, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-05-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 127, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-12-17', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 128, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-09-05', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 129, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2003-12-14', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 130, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-06-29', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 131, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2003-12-12', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 132, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-08-09', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 133, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-01-13', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 134, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1990-10-30', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 135, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-05-26', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 136, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '1998-03-13', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 137, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2003-12-03', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 138, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-04-26', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 139, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2005-09-27', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 140, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2004-10-15', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 141, 'gender' => 'perempuan', 'semester' => 8, 'birthdate' => '2004-12-11', 'jurusan' => 'Sistem dan Teknologi Informatika'],
            ['user_id' => 142, 'gender' => 'laki-laki', 'semester' => 8, 'birthdate' => '2000-06-26', 'jurusan' => 'Sistem dan Teknologi Informatika'],
        ];

        
        DB::table('mahasiswas')->insert($dataUser);
    }
}
